project:
  title: "Alin Mechenici {En} "
  output-dir: ./_site/en

website:
  navbar:
    right:
      - href: posts.qmd
        text: Articles
      - href: events.qmd
        text: Events
      - href: ../ro
        text: Romana

lang: en

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    highlight-style: espresso
    toc: true
    fontsize: 1.1em
    linestretch: 1.7